/**
 * @bounded-systems/schema-gen — project zod schemas to explicit, fast-types-clean
 * TypeScript, so a package can author validation in zod without forfeiting JSR
 * fast-types (zod's inferred types are too generic for JSR's fast analyzer).
 *
 *   zod schema ──z.toJSONSchema──▶ JSON Schema ──json-schema-to-typescript──▶ explicit .ts
 *
 * Keep the schema internal; generate the explicit public type; expose a `parse()`
 * boundary. Each schema's `.describe()` (field- and object-level) becomes JSDoc on
 * the generated type, so the schema is the single source for validation, types,
 * AND docs. Optional props get `| undefined` for `exactOptionalPropertyTypes`
 * parity with `z.infer`.
 *
 * Requires zod v4 (for `z.toJSONSchema`).
 */
import { readFileSync, writeFileSync } from "node:fs";

import { compile } from "json-schema-to-typescript";
import { z, type ZodType } from "zod";

/** A schema paired with the public type name to generate for it. */
export type SchemaEntry = readonly [schema: ZodType, typeName: string];

/** Options for {@link genSchemaTypes}. */
export interface GenOptions {
  /** Check mode: don't write; report drift via {@link GenResult.drift} instead. */
  check?: boolean;
  /** Banner prepended to the generated file. A sensible default is used when omitted. */
  banner?: string;
}

/** The result of a {@link genSchemaTypes} run. */
export interface GenResult {
  /** The generated file content. */
  content: string;
  /** In check mode: whether the on-disk file differs from {@link GenResult.content}. */
  drift: boolean;
}

const DEFAULT_BANNER =
  "// @generated by @bounded-systems/schema-gen — DO NOT EDIT.\n" +
  "// Author the schema (with .describe()) and run your `schema:gen` script.\n\n";

// Optional props become `?: T | undefined` so the type is sound under
// `exactOptionalPropertyTypes` (matching what `z.infer` produces).
const exactOptional = (ts: string): string =>
  ts.replace(/^(\s+[\w"']+\?: )(.+);$/gm, (_full, head: string, type: string) =>
    type.includes("| undefined") ? `${head}${type};` : `${head}${type} | undefined;`,
  );

/**
 * Project each schema in `schemas` to an explicit TypeScript type and write them
 * to `outPath` (or, with `{ check: true }`, report whether the on-disk file is
 * stale without writing). Returns the generated content and the drift flag.
 */
export async function genSchemaTypes(
  schemas: readonly SchemaEntry[],
  outPath: string,
  opts: GenOptions = {},
): Promise<GenResult> {
  let body = "";
  for (const [schema, name] of schemas) {
    const json = z.toJSONSchema(schema, { target: "draft-7" }) as Record<string, unknown>;
    const ts = (await compile(json, name, { bannerComment: "", additionalProperties: false })).trim();
    body += exactOptional(ts) + "\n\n";
  }
  const content = (opts.banner ?? DEFAULT_BANNER) + body;

  if (opts.check) {
    let current = "";
    try {
      current = readFileSync(outPath, "utf8");
    } catch {
      /* missing file → drift */
    }
    return { content, drift: current.trim() !== content.trim() };
  }
  writeFileSync(outPath, content);
  return { content, drift: false };
}
